### ISSUE TITLE
Errors without useful debugging logs

### ISSUE THREAD

**Issue by stephenmathieson** [jwalton/gh-ecr-push#12]
I've been using this action for a couple months and everything has been going perfectly! It's been **super helpful, thank you!**

Unfortunately my builds have started failing this morning and I'm not sure why. The action fails but doesn't include sufficient information for me to debug. As result, I have two questions:

1. Would you be willing to accept a PR which adds more information to error logs?
2. Do you have any idea what's causing my deployment to fail? I'm simply seeing `Error: Command failed: aws sts get-caller-identity --output json`, which doesn't help me identify _why_ the command failed.

<details>
<summary>
Deployment logs
</summary>

```
Run jwalton/gh-ecr-push@v1
  with:
    access-key-id: ***
    secret-access-key: ***
    region: us-east-1
    local-image: billing-service:latest
    image: billing-service:2959019b
$ aws sts get-caller-identity --output json

<botocore.awsrequest.AWSRequest object at 0x7f505570a710>
child_process.js:660
    throw err;
    ^

Error: Command failed: aws sts get-caller-identity --output json

<botocore.awsrequest.AWSRequest object at 0x7f505570a710>

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/jwalton/gh-ecr-push/v1/main.js:16:12)
    at Object.<anonymous> (/home/runner/work/_actions/jwalton/gh-ecr-push/v1/main.js:28:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 255,
  signal: null,
  output: [
    null,
    '',
    '\n<botocore.awsrequest.AWSRequest object at 0x7f505570a710>\n'
  ],
  pid: 2530,
  stdout: '',
  stderr: '\n<botocore.awsrequest.AWSRequest object at 0x7f505570a710>\n'
}
```

</details>

**Comment by stephenmathieson** [comment]
The patch in #13 fixes the issue I'm facing. While debugging, I realized that there is no additional/helpful information to output. The `aws` tool is simply exiting with `255`, providing no error message. I do not think there's anything which can be done to improve debugging (at least for my particular problem).

Leaving this open for visibility, but I think my PR should be enough to close this.

**Comment by TomLaMantia** [comment]
I am also getting the issue @stephenmathieson mentions. This is something that has appeared out of the blue for me. 

Is there any way I can leverage #13 in my builds before this PR is merged?

Thanks :)

**Comment by stephenmathieson** [comment]
@TomLaMantia feel free to use the fork I created. I plan on keeping it updated until my patch lands here.

```yml
uses: dequelabs/gh-ecr-push@add-region-disable-pager
```

**Comment by jwalton** [comment]
Sorry for the slow merge.  Thanks @stephenmathieson for this fix!

**Comment by stephenmathieson** [comment]
I will be deleting the `@dequelabs` fork in the next couple of days. If you're using it, please update your workflow to point back at this action.
