### ISSUE TITLE
Multiple images in image property

### ISSUE THREAD

**Issue by uripre** [jwalton/gh-ecr-push#16]
The README.md says in regard to the image property:
`this can be a list of images, separated by commas e.g. "myimage:v1.2.0, myimage:latest".`

However, when I set the image tag to multiple tags in my case:

>    - name: Push to ECR
>       uses: jwalton/gh-ecr-push@v1.3.2
>       with:
>         access-key-id: ...
>         secret-access-key: ...
>         region: us-east-1
>         local-image: appname:latest
>         image: appname:1, appname:latest

It fails with the following error:

> docker tag appname:latest x.dkr.ecr.us-east-1.amazonaws.com/appname:1, appname:latest
> "docker tag" requires exactly 2 arguments.

It seems to me like it fails to support multiple images. WDYT?

**Comment by jwalton** [comment]
Hmm... This is [the line](https://github.com/jwalton/gh-ecr-push/blob/dc79198ca45d6a64d3b0ed48d29ef93dc4adf77c/main.js#L52) where we're trying to tag:

```js
        run(`docker tag ${imageToPush.localImage} ${uri}`);
```

 so it sounds like `uri` is "x.dkr.ecr.us-east-1.amazonaws.com/appname:1, appname:latest".  This is based on `remoteImage` which comes [from here](https://github.com/jwalton/gh-ecr-push/blob/dc79198ca45d6a64d3b0ed48d29ef93dc4adf77c/images.js#L30).  I have a meeting right now, but I'll try to dig into this in the afternoon.

**Comment by jwalton** [comment]
@uripre Try v1.3.3?

**Comment by uripre** [comment]
Works like a charm now, thanks @jwalton for the prompt fix !
