### ISSUE TITLE
Image builds failing with v1.3.4

### ISSUE THREAD

**Issue by Serneum** [jwalton/gh-ecr-push#18]
Builds in my org use your action and have been succeeding up until we noticed about 30 minutes ago. It looks like this may be related to the release of 1.3.4. It looks like the action is now trying to parse our non-semVer tags as semVer

It looks like v1.3.4 changed `defaults` to `default` and from `false` to `false` in https://github.com/jwalton/gh-ecr-push/commit/9054b426573b8302d8a99850067be6b4f31e872c#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R26. Was that change intentional?

**Comment by jwalton** [comment]
*sigh*  `defaults` to `default` was intentional because "defaults" isn't a valid key in action.yaml.  `false` to `"false"` was similar, because the value has to be a string.  But, the string `"false"` is truthy.  -_-  Fixed in 1.3.5.
