### ISSUE TITLE
Get output ECR Image url 

### ISSUE THREAD

**Issue by rafilkmp3** [jwalton/gh-ecr-push#5]
I need a way to get the image output to use in ECS deploy step, Can you help me do this ?

**Comment by jwalton** [comment]
Hey!  I'm not doing anything with ECR right now, so I have no way to test this, but I have a build of this action that I think will do what you want:

https://github.com/jwalton/gh-ecr-push/pull/6

You can give that a go by specifying that branch. Let me know if it works for you, and I'll merge it to master.
